apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tp02-mychart-nginx.fullname" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tp02-mychart-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tp02-mychart-nginx.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          